import { TopicRandomizer } from "../utils";

// export const BlogTopic = new TopicRandomizer(topics);
  
  // Array of topics
export const topics: string[] = [
    "Artificial Intelligence",
    "Machine Learning",
    "Deep Learning",
    "Natural Language Processing (NLP)",
    "Computer Vision",
    "Reinforcement Learning",
    "Robotics",
    "AI Ethics",
    "Neural Networks",
    "Cognitive Computing",
    "Internet of Things (IoT)",
    "Data Science",
    "Big Data",
    "Cloud Computing",
    "Quantum Computing",
    "Cybersecurity",
    "Blockchain Technology",
    "Cryptocurrency",
    "Smart Cities",
    "Edge Computing",
    "Augmented Reality (AR)",
    "Virtual Reality (VR)",
    "Mixed Reality (MR)",
    "5G Networks",
    "Autonomous Vehicles",
    "Chatbots and Conversational AI",
    "Autonomous Drones",
    "AI in Healthcare",
    "AI in Education",
    "AI in Finance",
    "AI in Retail",
    "AI in Manufacturing",
    "AI in Entertainment",
    "AI in Marketing",
    "Artificial General Intelligence (AGI)",
    "AI-driven Automation",
    "Programming Languages",
    "Web Development",
    "Mobile Development",
    "Frontend Development",
    "Backend Development",
    "Full-Stack Development",
    "Software Development Life Cycle (SDLC)",
    "Continuous Integration and Deployment (CI/CD)",
    "Version Control (Git)",
    "APIs and Web Services",
    "Microservices Architecture",
    "DevOps",
    "Serverless Computing",
    "Data Structures and Algorithms",
    "Object-Oriented Programming (OOP)",
    "Functional Programming",
    "Event-Driven Programming",
    "Cloud-Native Development",
    "Database Design",
    "NoSQL Databases",
    "SQL Databases",
    "Data Warehousing",
    "Data Engineering",
    "Data Analytics",
    "Predictive Analytics",
    "Data Visualization",
    "Business Intelligence (BI)",
    "Augmented Analytics",
    "Low-Code Development",
    "No-Code Development",
    "User Experience (UX) Design",
    "User Interface (UI) Design",
    "Human-Computer Interaction (HCI)",
    "Web Accessibility",
    "Cross-Platform Development",
    "Agile Software Development",
    "Scrum Framework",
    "Kanban",
    "Test-Driven Development (TDD)",
    "Cloud Platforms (AWS, Azure, Google Cloud)",
    "Containerization and Docker",
    "Kubernetes",
    "Serverless Frameworks",
    "Artificial Intelligence in Software Testing",
    "Continuous Testing",
    "Automation Testing",
    "Software Performance Optimization",
    "Web Security Best Practices",
    "Ethical Hacking",
    "Penetration Testing",
    "Privacy and Data Protection",
    "GDPR Compliance",
    "Digital Twins",
    "Blockchain in Supply Chain",
    "Cryptocurrency Mining",
    "NFTs (Non-Fungible Tokens)",
    "Smart Contracts",
    "Decentralized Applications (dApps)",
    "Internet Privacy",
    "Sustainable Technology",
    "Green Computing",
    "Quantum Cryptography",
    "Artificial Intelligence in Government",
    "AI for Social Good"
  ];
  
  
  export const BlogTopic = new TopicRandomizer(topics);
  
//   console.log(BlogTopic.getRandomTopic()); // Returns a random topic
//   console.log(BlogTopic.getRandomTopic()); // Returns a different random topic
  